
'use server';
/**
 * @fileOverview An AI agent that analyzes patient symptoms and provides a preliminary diagnosis, risk assessment, and a recommended next action.
 *
 * - analyzeSymptoms - A function that handles the symptom analysis process.
 * - AnalyzeSymptomsInput - The input type for the analyzeSymptoms function.
 * - AnalyzeSymptomsOutput - The return type for the analyzeSymptoms function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeSymptomsInputSchema = z.object({
  symptoms: z.string().describe('The symptoms described by the patient, either via voice or text.'),
});
export type AnalyzeSymptomsInput = z.infer<typeof AnalyzeSymptomsInputSchema>;

const AnalyzeSymptomsOutputSchema = z.object({
  preliminaryDiagnosis: z.string().describe('The preliminary diagnosis generated by AI.'),
  riskAssessment: z.string().describe('The risk assessment generated by AI (e.g., Low, Medium, High).'),
  confidenceScore: z.number().describe('The confidence score of the diagnosis (0-1).'),
  recommendedAction: z.string().describe('The single, most important next action for the healthcare worker to take.'),
});
export type AnalyzeSymptomsOutput = z.infer<typeof AnalyzeSymptomsOutputSchema>;

export async function analyzeSymptoms(input: AnalyzeSymptomsInput): Promise<AnalyzeSymptomsOutput> {
  return analyzeSymptomsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeSymptomsPrompt',
  input: {schema: AnalyzeSymptomsInputSchema},
  output: {schema: AnalyzeSymptomsOutputSchema},
  prompt: `You are an AI assistant that helps Community Health Workers (CHWs) assess patients.

You will receive a description of the patient's symptoms. Based on these symptoms, you will provide:
1. A preliminary diagnosis.
2. A risk assessment (Low, Medium, or High).
3. A confidence score for the diagnosis, between 0 and 1.
4. A single, clear, and actionable "Next Best Action" for the CHW. This action should be the most critical next step, for example: "Recommend performing a rapid diagnostic test for malaria," or "Suggest scheduling a follow-up check in 3 days," or "Advise immediate referral to the nearest clinic."

Symptoms: {{{symptoms}}}`,
});

const analyzeSymptomsFlow = ai.defineFlow(
  {
    name: 'analyzeSymptomsFlow',
    inputSchema: AnalyzeSymptomsInputSchema,
    outputSchema: AnalyzeSymptomsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
